// <auto-generated/>

namespace SharpGen.Runtime
{
    [System.Runtime.InteropServices.GuidAttribute("00000000-0000-0000-C000-000000000046")]
    public partial class ComObject : SharpGen.Runtime.CppObject, SharpGen.Runtime.IUnknown
    {
        public ComObject(System.IntPtr nativePtr): base (nativePtr)
        {
        }

        public static explicit operator ComObject(System.IntPtr nativePtr) => nativePtr == System.IntPtr.Zero ? null : new ComObject(nativePtr);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "riid">No documentation.</param>
        /// <param name = "vObjectOut">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HRESULT IUnknown::QueryInterface([In] const GUID&amp; riid,[Out] void** ppvObject)</unmanaged>
        /// <unmanaged-short>IUnknown::QueryInterface</unmanaged-short>
        public unsafe SharpGen.Runtime.Result QueryInterface(System.Guid riid, out System.IntPtr vObjectOut)
        {
            SharpGen.Runtime.Result __result__;
            fixed (void *vObjectOut_ = &vObjectOut)
                __result__ = SharpGen.Runtime.COM.LocalInterop.CalliStdCallint(this._nativePointer, &riid, vObjectOut_, (*(void ***)this._nativePointer)[0]);
            return __result__;
        }

        /// <summary>
        /// No documentation.
        /// </summary>
        /// <returns>No documentation.</returns>
        /// <unmanaged>ULONG IUnknown::AddRef()</unmanaged>
        /// <unmanaged-short>IUnknown::AddRef</unmanaged-short>
        public unsafe System.UInt32 AddRef()
        {
            System.UInt32 __result__;
            __result__ = SharpGen.Runtime.COM.LocalInterop.CalliStdCallSystemUInt32(this._nativePointer, (*(void ***)this._nativePointer)[1]);
            return __result__;
        }

        /// <summary>
        /// No documentation.
        /// </summary>
        /// <returns>No documentation.</returns>
        /// <unmanaged>ULONG IUnknown::Release()</unmanaged>
        /// <unmanaged-short>IUnknown::Release</unmanaged-short>
        public unsafe System.UInt32 Release()
        {
            System.UInt32 __result__;
            __result__ = SharpGen.Runtime.COM.LocalInterop.CalliStdCallSystemUInt32(this._nativePointer, (*(void ***)this._nativePointer)[2]);
            return __result__;
        }
    }

    [System.Runtime.InteropServices.GuidAttribute("00000000-0000-0000-C000-000000000046")]
    public partial interface IUnknown : SharpGen.Runtime.ICallbackable
    {
    }
}