// <auto-generated/>

namespace SharpGen.Runtime.COM
{
    internal static partial class LocalInterop
    {
        public static unsafe int CalliStdCallint(void *thisObject, void *param0, void *param1, void *methodPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliStdCallSystemUInt32(void *thisObject, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, void *param0, System.UInt32 param1, void *param2, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, long param0, System.UInt32 param1, void *param2, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, System.UInt64 param0, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, void *param0, System.UInt64 param1, void *param2, void *param3, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, int param0, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, System.UInt64 param0, System.UInt64 param1, int param2, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, void *param0, int param1, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallint(void *thisObject, void *param0, void *methodPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallFuncint(void *param0, System.UInt32 param1, void *param2, void *funcPtr)
        {
            throw null;
        }
    }
}