// <auto-generated/>

namespace SharpGen.Runtime.Win32
{
    [System.FlagsAttribute]
    /// <summary>
    /// No documentation.
    /// </summary>
    /// <unmanaged>STGC</unmanaged>
    /// <unmanaged-short>STGC</unmanaged-short>
    public enum CommitFlags : System.Int32
    {
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>STGC_DEFAULT</unmanaged>
        /// <unmanaged-short>STGC_DEFAULT</unmanaged-short>
        Default = unchecked ((System.Int32)(0)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>STGC_OVERWRITE</unmanaged>
        /// <unmanaged-short>STGC_OVERWRITE</unmanaged-short>
        Overwrite = unchecked ((System.Int32)(1)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>STGC_ONLYIFCURRENT</unmanaged>
        /// <unmanaged-short>STGC_ONLYIFCURRENT</unmanaged-short>
        OnlyCurrent = unchecked ((System.Int32)(2)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>STGC_DANGEROUSLYCOMMITMERELYTODISKCACHE</unmanaged>
        /// <unmanaged-short>STGC_DANGEROUSLYCOMMITMERELYTODISKCACHE</unmanaged-short>
        DangerouslyCommitMerelyToDiskCache = unchecked ((System.Int32)(4)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>STGC_CONSOLIDATE</unmanaged>
        /// <unmanaged-short>STGC_CONSOLIDATE</unmanaged-short>
        Consolidate = unchecked ((System.Int32)(8))}

    [System.FlagsAttribute]
    /// <summary>
    /// No documentation.
    /// </summary>
    /// <unmanaged>LOCKTYPE</unmanaged>
    /// <unmanaged-short>LOCKTYPE</unmanaged-short>
    public enum LockType : System.Int32
    {
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>LOCK_WRITE</unmanaged>
        /// <unmanaged-short>LOCK_WRITE</unmanaged-short>
        Write = unchecked ((System.Int32)(1)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>LOCK_EXCLUSIVE</unmanaged>
        /// <unmanaged-short>LOCK_EXCLUSIVE</unmanaged-short>
        Exclusive = unchecked ((System.Int32)(2)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>LOCK_ONLYONCE</unmanaged>
        /// <unmanaged-short>LOCK_ONLYONCE</unmanaged-short>
        OnlyOnce = unchecked ((System.Int32)(4))}

    [System.FlagsAttribute]
    /// <summary>
    /// No documentation.
    /// </summary>
    /// <unmanaged>STATFLAG</unmanaged>
    /// <unmanaged-short>STATFLAG</unmanaged-short>
    public enum StorageStatisticsFlags : System.Int32
    {
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>STATFLAG_DEFAULT</unmanaged>
        /// <unmanaged-short>STATFLAG_DEFAULT</unmanaged-short>
        Default = unchecked ((System.Int32)(0)),
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>STATFLAG_NONAME</unmanaged>
        /// <unmanaged-short>STATFLAG_NONAME</unmanaged-short>
        NoName = unchecked ((System.Int32)(1)),
        /// <summary>
        /// None
        /// </summary>
        /// <unmanaged>None</unmanaged>
        /// <unmanaged-short>None</unmanaged-short>
        None = unchecked ((System.Int32)(0))}
}