// <auto-generated/>

namespace SharpGen.Runtime.Win32
{
    /// <summary>
    /// Functions
    /// </summary>
    internal static partial class WinRTStrings
    {
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "sourceString">No documentation.</param>
        /// <param name = "length">No documentation.</param>
        /// <param name = "text">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HRESULT WindowsCreateString([In, Buffer, Optional] const wchar_t* sourceString,[In] unsigned int length,[Out, Optional] HSTRING* string)</unmanaged>
        /// <unmanaged-short>WindowsCreateString</unmanaged-short>
        public static unsafe void WindowsCreateString(System.String sourceString, System.UInt32 length, out System.IntPtr text)
        {
            SharpGen.Runtime.Result __result__;
            fixed (void *text_ = &text)
                fixed (char *sourceString_ = sourceString)
                    __result__ = WindowsCreateString_((void *)sourceString_, length, text_);
            __result__.CheckError();
        }

        [System.Runtime.InteropServices.DllImportAttribute("api-ms-win-core-winrt-string-l1", EntryPoint = "WindowsCreateString", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern int WindowsCreateString_(void *param0, System.UInt32 param1, void *param2);
    }
}