// <auto-generated/>

namespace SharpGen.Runtime.Win32
{
    /// <summary>
    /// No documentation.
    /// </summary>
    /// <unmanaged>STATSTG</unmanaged>
    /// <unmanaged-short>STATSTG</unmanaged-short>
    public partial struct StorageStatistics
    {
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>pwcsName</unmanaged>
        /// <unmanaged-short>pwcsName</unmanaged-short>
        public System.String PwcsName;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>type</unmanaged>
        /// <unmanaged-short>type</unmanaged-short>
        public System.Int32 Type;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>cbSize</unmanaged>
        /// <unmanaged-short>cbSize</unmanaged-short>
        public System.UInt64 CbSize;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>mtime</unmanaged>
        /// <unmanaged-short>mtime</unmanaged-short>
        public System.Int64 Mtime;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>ctime</unmanaged>
        /// <unmanaged-short>ctime</unmanaged-short>
        public System.Int64 Ctime;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>atime</unmanaged>
        /// <unmanaged-short>atime</unmanaged-short>
        public System.Int64 Atime;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>grfMode</unmanaged>
        /// <unmanaged-short>grfMode</unmanaged-short>
        public System.Int32 GrfMode;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>grfLocksSupported</unmanaged>
        /// <unmanaged-short>grfLocksSupported</unmanaged-short>
        public System.Int32 GrfLocksSupported;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>clsid</unmanaged>
        /// <unmanaged-short>clsid</unmanaged-short>
        public System.Guid Clsid;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>grfStateBits</unmanaged>
        /// <unmanaged-short>grfStateBits</unmanaged-short>
        public System.Int32 GrfStateBits;
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <unmanaged>reserved</unmanaged>
        /// <unmanaged-short>reserved</unmanaged-short>
        public System.Int32 Reserved;
        [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential, Pack = 0, CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
        internal partial struct __Native
        {
            public System.IntPtr PwcsName;
            public System.Int32 Type;
            public System.UInt64 CbSize;
            public System.Int64 Mtime;
            public System.Int64 Ctime;
            public System.Int64 Atime;
            public System.Int32 GrfMode;
            public System.Int32 GrfLocksSupported;
            public System.Guid Clsid;
            public System.Int32 GrfStateBits;
            public System.Int32 Reserved;
        }

        internal unsafe void __MarshalFree(ref __Native @ref)
        {
            System.Runtime.InteropServices.Marshal.FreeHGlobal(@ref.PwcsName);
        }

        internal unsafe void __MarshalFrom(ref __Native @ref)
        {
            PwcsName = System.Runtime.InteropServices.Marshal.PtrToStringUni(@ref.PwcsName);
            Type = @ref.Type;
            CbSize = @ref.CbSize;
            Mtime = @ref.Mtime;
            Ctime = @ref.Ctime;
            Atime = @ref.Atime;
            GrfMode = @ref.GrfMode;
            GrfLocksSupported = @ref.GrfLocksSupported;
            Clsid = @ref.Clsid;
            GrfStateBits = @ref.GrfStateBits;
            Reserved = @ref.Reserved;
        }

        internal unsafe void __MarshalTo(ref __Native @ref)
        {
            @ref.PwcsName = System.Runtime.InteropServices.Marshal.StringToHGlobalUni(PwcsName);
            @ref.Type = Type;
            @ref.CbSize = CbSize;
            @ref.Mtime = Mtime;
            @ref.Ctime = Ctime;
            @ref.Atime = Atime;
            @ref.GrfMode = GrfMode;
            @ref.GrfLocksSupported = GrfLocksSupported;
            @ref.Clsid = Clsid;
            @ref.GrfStateBits = GrfStateBits;
            @ref.Reserved = Reserved;
        }
    }
}